name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Google Chrome install
      run: |
          chmod +x ./InstallChrome.sh
          ./InstallChrome.sh

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Display test results
      run: cat target/surefire-reports/*.txt || true
